site_name: Jetson Isaac ROS Visual SLAM Tutorial
theme:
    name: "material"
    favicon: images/m48-document-support-guide-256px-wht.png
    logo: images/m48-document-support-guide-256px-wht.png
    font: 
      text: Incosolata
    palette:
      - media: "(prefers-color-scheme: light)" 
        scheme: nvgreen
        toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)" 
        scheme: slate
        toggle:
            icon: material/toggle-switch
            name: Switch to light mode
    features:
       - navigation.indexes
       - navigation.expand
       - content.tabs.link
       - content.code.copy

repo_url: https://github.com/NVIDIA-AI-IOT/jetson_isaac_ros_visual_slam_tutorial/

plugins:
  - search
use_directory_urls: false

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 

extra_css:
  - css/colors.css

nav:

  - Home: index.md
  - Quickstart: quickstart.md
  - Next Steps: nextsteps.md
  - SD card image: sdcard.md
  - Where to buy: buy.md

extra:
  analytics:
    provider: google
    property: G-0LQ6PLRJQZ
  
